apiVersion: apps/v1
kind: Deployment
metadata:
  name: myd1
  labels:
    app: myapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: c1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
